name: kafe_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  provider: ^6.1.4
  google_fonts: ^6.2.1
  go_router: ^14.8.1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/trophy.json
    - assets/animations/drying.json
    - assets/animations/blending.json
    - assets/images/kafeiculteur.png

